# Notebook 04b — Decision Engine for Predicted Late-Stage Clone Selection

## Goal

This notebook converts **predicted late-stage outcomes** from Notebook 03b into an actual clone selection decision.

We assume:

- at selection time, **true late outcomes are unknown**
- only **early-stage measurements** are available in real deployment
- Notebook 03b provides predicted late-stage qP, qP drop, aggregation, and stability probability
- Notebook 04b applies selection rules to recommend clones

---

## Why this notebook exists

Notebook 03b is the **prediction engine**:
- it predicts future clone performance

Notebook 04b is the **decision engine**:
- it applies operational rules
- filters risky clones
- ranks the remaining candidates
- simulates how clone selection would work in practice

This separation is useful because:
- prediction and decision are different tasks
- thresholds can change without retraining models
- future SDL systems may add rescue / process-control logic here

---

## Current decision logic

We currently use this deployment-style selection framework:

1. **Quality filter**
   - remove clones with predicted late aggregation above threshold

2. **Stability filter**
   - remove clones with low predicted stability probability

3. **Productivity ranking**
   - among remaining clones, rank by predicted late qP

---

## Decision modes

We compare two modes:

### A. Biosimilar mode
- productivity is emphasized
- stability is important
- aggregation penalty is lighter

### B. Novel / ADC mode
- quality is emphasized more strongly
- stability remains important
- productivity still matters, but quality threshold is stricter

---

## Important note

All `true_*` columns are used **only for offline evaluation in synthetic data**.

In real deployment:
- only `pred_*` columns would be available

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.stats import spearmanr

scenario = "legacy"   # or "optimized"
n_clones = 5000

TOP_N = 10
TOP_STAGE2 = 3

print("Scenario:", scenario)
print("n_clones:", n_clones)
print("Top-N final:", TOP_N)
print("Top-N stage2:", TOP_STAGE2)

Scenario: legacy
n_clones: 5000
Top-N final: 10
Top-N stage2: 3

## Step 1 — Load prediction table from Notebook 03b

Here we load the prediction table produced in Notebook 03b.

This table should already contain:

- predicted late qP
- predicted qP drop
- predicted late aggregation
- predicted stable probability
- true late outcomes for offline simulation only

In [2]:
PRED_PATH = Path("../data/synthetic/processed") / f"predictions_03b_qp_{n_clones}_{scenario}.csv"
print("Loading predictions:", PRED_PATH)

df = pd.read_csv(PRED_PATH)
print("Shape:", df.shape)
display(df.head())

Loading predictions: ../data/synthetic/processed/predictions_03b_qp_5000_legacy.csv
Shape: (1000, 12)

,clone_id,pred_qp_drop,pred_late_qp,pred_late_agg,pred_stable_prob,pred_stable_label,true_qp_drop,true_late_qp,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
0,CLONE_1502,0.410998,2.718882e-08,9.361901,0.407925,0,0.519438,2.236766e-08,6.841477,0,0.001384,0.000000
1,CLONE_2587,0.442873,7.243343e-08,3.072783,0.200133,0,0.646408,4.849476e-08,4.346930,0,0.000000,0.000000
2,CLONE_2654,0.442450,2.796240e-08,8.352367,0.255974,0,0.457481,2.481724e-08,9.193986,0,0.004473,0.000000
3,CLONE_1056,0.424634,6.269522e-08,7.246007,0.290806,0,0.387697,6.751316e-08,3.772907,0,0.002981,0.000000
4,CLONE_0706,0.604853,1.843651e-07,9.071856,0.017820,0,0.675360,1.487222e-07,7.045437,0,0.003000,0.008844

## Step 2 — Check schema compatibility

Before applying selection rules, we verify that the prediction table matches the expected 03b output schema.

This prevents silent notebook mismatch caused by:
- outdated file names
- old column naming
- partial notebook updates

In [3]:
required_cols = [
    "clone_id",
    "pred_late_qp",
    "pred_qp_drop",
    "pred_late_agg",
    "pred_stable_prob",
    "pred_stable_label",
    "true_late_qp",
    "true_qp_drop",
    "true_late_agg",
    "true_stable_label",
]

missing = [c for c in required_cols if c not in df.columns]
print("Missing required columns:", missing)
assert len(missing) == 0, f"04b is missing required columns: {missing}"

optional_cols = ["pred_super_prob", "pred_aggr_prob"]
present_optional = [c for c in optional_cols if c in df.columns]
print("Optional columns found:", present_optional)

Missing required columns: []
Optional columns found: ['pred_super_prob', 'pred_aggr_prob']

## Step 3 — Define helper functions

We use helper functions for:

- z-score normalization
- ranking utility calculation
- top-k overlap
- elite capture metrics

These help compare decision quality across selection modes.

In [4]:
def z(s):
    s = pd.Series(s).astype(float)
    return (s - s.mean()) / (s.std(ddof=0) + 1e-9)

def make_pred_utility(df, w_qp, w_drop, w_agg):
    return (
        w_qp * z(df["pred_late_qp"])
        - w_drop * z(df["pred_qp_drop"])
        - w_agg * z(df["pred_late_agg"])
    )

def make_true_utility(df, w_qp, w_drop, w_agg):
    return (
        w_qp * z(df["true_late_qp"])
        - w_drop * z(df["true_qp_drop"])
        - w_agg * z(df["true_late_agg"])
    )

def topk_overlap(true_scores, pred_scores, k):
    true_top = set(pd.Series(true_scores).nlargest(k).index)
    pred_top = set(pd.Series(pred_scores).nlargest(k).index)
    return len(true_top & pred_top) / k

def precision_at_k_df(df, score_col, elite_col, k):
    top = df.sort_values(score_col, ascending=False).head(k)
    return float(top[elite_col].mean())

def ndcg_at_k_df(df, score_col, elite_col, k):
    top = df.sort_values(score_col, ascending=False).head(k)
    rel = top[elite_col].values.astype(float)
    discounts = 1.0 / np.log2(np.arange(2, len(rel) + 2))
    dcg = float(np.sum(rel * discounts))
    ideal = np.sort(rel)[::-1]
    idcg = float(np.sum(ideal * discounts)) + 1e-12
    return dcg / idcg

## Step 4 — Define offline evaluation utilities

Because this is a synthetic dataset, we can define an offline “true utility” score
to evaluate how good the selected clones really are.

This is **evaluation only** and would not be available in real deployment.

In [5]:
# biosimilar-style evaluation utility
W_BIO = dict(w_qp=1.0, w_drop=1.0, w_agg=0.2)

# novel / ADC-style evaluation utility
W_NOVEL = dict(w_qp=1.0, w_drop=1.0, w_agg=1.0)

df["true_util_bio"] = make_true_utility(df, **W_BIO)
df["true_util_novel"] = make_true_utility(df, **W_NOVEL)

df["pred_util_bio"] = make_pred_utility(df, **W_BIO)
df["pred_util_novel"] = make_pred_utility(df, **W_NOVEL)

display(df[[
    "clone_id",
    "true_util_bio", "pred_util_bio",
    "true_util_novel", "pred_util_novel"
]].head())

     clone_id  true_util_bio  pred_util_bio  true_util_novel  pred_util_novel
0  CLONE_1502      -0.557079      -0.230904        -0.652615        -1.126395
1  CLONE_2587      -1.174779       0.068241        -0.630865         1.063447
2  CLONE_2654      -0.325551      -0.442143        -1.024127        -1.034138
3  CLONE_1056       0.459992      -0.103451         1.151051        -0.362841
4  CLONE_0706      -1.507217      -1.576131        -1.655036        -2.384426

## Step 5A — Decision mode: Biosimilar

In biosimilar mode, the selection logic is:

1. remove clones with poor predicted quality
2. remove clones with low predicted stability probability
3. rank the remaining clones by predicted late qP

This reflects a setting where:
- productivity matters strongly
- stability matters strongly
- aggregation still matters, but slightly less than in novel mode

In [6]:
# --------------------------------------------------
# Step 5A — Biosimilar 3-bucket decision engine
# --------------------------------------------------

BIO_AGG_MAX = 15.0
BIO_STABLE_PROB_MIN = 0.50

# rescue margin (핵심 파라미터)
MARGIN_AGG = 3.0
MARGIN_STABLE = 0.10

bio = df.copy()

# ---------------------------
# Bucket definitions
# ---------------------------

# PASS (strict)
bio["pass_quality"] = bio["pred_late_agg"] <= BIO_AGG_MAX
bio["pass_stability"] = bio["pred_stable_prob"] >= BIO_STABLE_PROB_MIN
bio["bucket_pass"] = bio["pass_quality"] & bio["pass_stability"]

# RESCUE (borderline)
bio["near_quality"] = bio["pred_late_agg"].between(BIO_AGG_MAX, BIO_AGG_MAX + MARGIN_AGG)
bio["near_stability"] = bio["pred_stable_prob"].between(
    BIO_STABLE_PROB_MIN - MARGIN_STABLE,
    BIO_STABLE_PROB_MIN
)

bio["high_prod"] = bio["pred_late_qp"] >= bio["pred_late_qp"].quantile(0.80)

bio["bucket_rescue"] = (
    (~bio["bucket_pass"]) &
    bio["high_prod"] &
    (bio["near_quality"] | bio["near_stability"])
)

# FAIL
bio["bucket_fail"] = ~(bio["bucket_pass"] | bio["bucket_rescue"])

# ---------------------------
# Ranking
# ---------------------------
bio_pass = bio[bio["bucket_pass"]].copy()
bio_rescue = bio[bio["bucket_rescue"]].copy()

bio_pass["rank_metric"] = bio_pass["pred_late_qp"]
bio_rescue["rank_metric"] = bio_rescue["pred_late_qp"]

bio_pass = bio_pass.sort_values("rank_metric", ascending=False)
bio_rescue = bio_rescue.sort_values("rank_metric", ascending=False)

# ---------------------------
# Stage selection
# ---------------------------
P10_PASS_N = 120
P10_RESCUE_N = 30

bio_stage1_pass = bio_pass.head(P10_PASS_N)
bio_stage1_rescue = bio_rescue.head(P10_RESCUE_N)

print("=== Biosimilar Stage 1 (P10) ===")
print("Pass:", len(bio_stage1_pass))
print("Rescue:", len(bio_stage1_rescue))
print("Fail:", int(bio["bucket_fail"].sum()))

display(bio_stage1_pass.head())
display(bio_stage1_rescue.head())

=== Biosimilar Stage 1 (P10) ===
Pass: 79
Rescue: 16
Fail: 905

,clone_id,pred_qp_drop,pred_late_qp,pred_late_agg,pred_stable_prob,pred_stable_label,true_qp_drop,true_late_qp,true_late_agg,true_stable_label,...,pred_util_novel,pass_quality,pass_stability,bucket_pass,near_quality,near_stability,high_prod,bucket_rescue,bucket_fail,rank_metric
621,CLONE_3254,0.302129,4.414624e-06,8.575735,0.553073,1,0.204801,7.251734e-06,9.310199,1,...,11.760114,True,True,True,False,False,True,False,False,4.414624e-06
314,CLONE_1619,0.208336,2.235499e-06,3.074035,0.890761,1,0.141343,2.452274e-06,4.494834,1,...,8.933342,True,True,True,False,False,True,False,False,2.235499e-06
476,CLONE_2759,0.269152,9.587370e-07,12.221503,0.686770,1,0.052569,1.205105e-06,14.293786,1,...,1.563927,True,True,True,False,False,True,False,False,9.587370e-07
898,CLONE_3393,0.296605,7.761064e-07,8.548195,0.621659,1,0.360523,7.938732e-07,5.284487,0,...,2.209466,True,True,True,False,False,True,False,False,7.761064e-07
490,CLONE_0355,0.303608,5.121093e-07,7.481896,0.574696,1,0.419802,4.564358e-07,7.810760,0,...,1.848390,True,True,True,False,False,True,False,False,5.121093e-07

,clone_id,pred_qp_drop,pred_late_qp,pred_late_agg,pred_stable_prob,pred_stable_label,true_qp_drop,true_late_qp,true_late_agg,true_stable_label,...,pred_util_novel,pass_quality,pass_stability,bucket_pass,near_quality,near_stability,high_prod,bucket_rescue,bucket_fail,rank_metric
180,CLONE_4625,0.299615,4.679723e-06,9.050570,0.496845,0,0.145687,1.506612e-05,9.728748,1,...,12.305091,True,False,False,False,True,True,True,False,4.679723e-06
839,CLONE_2723,0.351533,5.682729e-07,2.999796,0.418388,0,0.354275,5.814427e-07,2.434674,0,...,3.240471,True,False,False,False,True,True,True,False,5.682729e-07
537,CLONE_3608,0.354727,2.865344e-07,2.373854,0.414739,0,0.394365,2.740198e-07,2.406392,0,...,2.702064,True,False,False,False,True,True,True,False,2.865344e-07
663,CLONE_1045,0.305171,2.838497e-07,7.551278,0.493955,0,0.356933,2.645873e-07,9.767784,0,...,1.204959,True,False,False,False,True,True,True,False,2.838497e-07
845,CLONE_4507,0.331586,2.747384e-07,7.717776,0.481751,0,0.283278,2.956017e-07,5.788807,1,...,0.875473,True,False,False,False,True,True,True,False,2.747384e-07

In [7]:
# --------------------------------------------------
# Stage 2 (P15) refinement
# --------------------------------------------------

# Combine pass + rescue from Stage 1
stage2_pool = pd.concat([bio_stage1_pass, bio_stage1_rescue], ignore_index=True)

# re-rank (같은 metric 유지 or utility 써도 OK)
stage2_pool["rank_metric"] = stage2_pool["pred_late_qp"]

stage2_pool = stage2_pool.sort_values("rank_metric", ascending=False)

P15_PASS_N = 25
P15_RESCUE_N = 8

stage2_pass = stage2_pool.head(P15_PASS_N)
stage2_rescue = stage2_pool.iloc[P15_PASS_N:P15_PASS_N + P15_RESCUE_N]

print("=== Stage 2 (P15) ===")
print("Pass:", len(stage2_pass))
print("Rescue:", len(stage2_rescue))

display(stage2_pass.head())
display(stage2_rescue.head())

=== Stage 2 (P15) ===
Pass: 25
Rescue: 8

,clone_id,pred_qp_drop,pred_late_qp,pred_late_agg,pred_stable_prob,pred_stable_label,true_qp_drop,true_late_qp,true_late_agg,true_stable_label,...,pred_util_novel,pass_quality,pass_stability,bucket_pass,near_quality,near_stability,high_prod,bucket_rescue,bucket_fail,rank_metric
79,CLONE_4625,0.299615,4.679723e-06,9.050570,0.496845,0,0.145687,1.506612e-05,9.728748,1,...,12.305091,True,False,False,False,True,True,True,False,4.679723e-06
0,CLONE_3254,0.302129,4.414624e-06,8.575735,0.553073,1,0.204801,7.251734e-06,9.310199,1,...,11.760114,True,True,True,False,False,True,False,False,4.414624e-06
1,CLONE_1619,0.208336,2.235499e-06,3.074035,0.890761,1,0.141343,2.452274e-06,4.494834,1,...,8.933342,True,True,True,False,False,True,False,False,2.235499e-06
2,CLONE_2759,0.269152,9.587370e-07,12.221503,0.686770,1,0.052569,1.205105e-06,14.293786,1,...,1.563927,True,True,True,False,False,True,False,False,9.587370e-07
3,CLONE_3393,0.296605,7.761064e-07,8.548195,0.621659,1,0.360523,7.938732e-07,5.284487,0,...,2.209466,True,True,True,False,False,True,False,False,7.761064e-07

,clone_id,pred_qp_drop,pred_late_qp,pred_late_agg,pred_stable_prob,pred_stable_label,true_qp_drop,true_late_qp,true_late_agg,true_stable_label,...,pred_util_novel,pass_quality,pass_stability,bucket_pass,near_quality,near_stability,high_prod,bucket_rescue,bucket_fail,rank_metric
23,CLONE_4741,0.279822,2.995351e-07,6.229174,0.751862,1,0.127000,3.739542e-07,8.055819,1,...,1.976275,True,True,True,False,False,True,False,False,2.995351e-07
81,CLONE_3608,0.354727,2.865344e-07,2.373854,0.414739,0,0.394365,2.740198e-07,2.406392,0,...,2.702064,True,False,False,False,True,True,True,False,2.865344e-07
82,CLONE_1045,0.305171,2.838497e-07,7.551278,0.493955,0,0.356933,2.645873e-07,9.767784,0,...,1.204959,True,False,False,False,True,True,True,False,2.838497e-07
24,CLONE_2226,0.298040,2.820449e-07,5.473257,0.650354,1,0.318427,2.749554e-07,7.448462,0,...,2.046649,True,True,True,False,False,True,False,False,2.820449e-07
83,CLONE_4507,0.331586,2.747384e-07,7.717776,0.481751,0,0.283278,2.956017e-07,5.788807,1,...,0.875473,True,False,False,False,True,True,True,False,2.747384e-07

In [8]:
# --------------------------------------------------
# Final selection from Stage 2 pool
# --------------------------------------------------

FINAL_TOP_N = TOP_N      # usually 10
FINAL_TOP3 = TOP_STAGE2  # usually 3

final_pool = pd.concat([stage2_pass, stage2_rescue], ignore_index=True)
final_pool = final_pool.sort_values(
    ["pred_late_qp", "pred_stable_prob"],
    ascending=[False, False]
).copy()

bio_top10 = final_pool.head(FINAL_TOP_N).copy()
bio_top3 = final_pool.head(FINAL_TOP3).copy()

print("=== Biosimilar Final Selection ===")
print("Final top10:", len(bio_top10))
print("Final top3:", len(bio_top3))

display(bio_top10[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in bio_top10.columns]])

display(bio_top3[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in bio_top3.columns]])

=== Biosimilar Final Selection ===
Final top10: 10
Final top3: 3

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
0,CLONE_4625,4.679723e-06,0.299615,9.050570,0.496845,1.506612e-05,0.145687,9.728748,1,0.728240,0.008469
1,CLONE_3254,4.414624e-06,0.302129,8.575735,0.553073,7.251734e-06,0.204801,9.310199,1,0.501185,0.025047
2,CLONE_1619,2.235499e-06,0.208336,3.074035,0.890761,2.452274e-06,0.141343,4.494834,1,0.920042,0.000000
3,CLONE_2759,9.587370e-07,0.269152,12.221503,0.686770,1.205105e-06,0.052569,14.293786,1,0.611315,0.003856
4,CLONE_3393,7.761064e-07,0.296605,8.548195,0.621659,7.938732e-07,0.360523,5.284487,0,0.511244,0.000000
5,CLONE_2723,5.682729e-07,0.351533,2.999796,0.418388,5.814427e-07,0.354275,2.434674,0,0.342118,0.000000
6,CLONE_0355,5.121093e-07,0.303608,7.481896,0.574696,4.564358e-07,0.419802,7.810760,0,0.214447,0.000000
7,CLONE_1035,5.067668e-07,0.324348,8.473888,0.573182,4.534849e-07,0.427422,8.809331,0,0.266635,0.000000
8,CLONE_4119,4.826748e-07,0.325585,3.773155,0.533421,4.881243e-07,0.292383,2.908559,1,0.212179,0.000000
9,CLONE_2358,4.766879e-07,0.290741,4.977838,0.661406,5.567181e-07,0.197321,4.869253,1,0.225138,0.000000

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
0,CLONE_4625,0.000005,0.299615,9.050570,0.496845,0.000015,0.145687,9.728748,1,0.728240,0.008469
1,CLONE_3254,0.000004,0.302129,8.575735,0.553073,0.000007,0.204801,9.310199,1,0.501185,0.025047
2,CLONE_1619,0.000002,0.208336,3.074035,0.890761,0.000002,0.141343,4.494834,1,0.920042,0.000000

In [9]:
def eval_selection(df_sel, label="selection"):
    return {
        "label": label,
        "n": len(df_sel),
        "mean_true_late_qp": float(df_sel["true_late_qp"].mean()),
        "mean_true_qp_drop": float(df_sel["true_qp_drop"].mean()),
        "mean_true_late_agg": float(df_sel["true_late_agg"].mean()),
        "stable_rate": float(df_sel["true_stable_label"].mean()),
    }

bio_eval_table = pd.DataFrame([
    eval_selection(bio_stage1_pass, "bio_P10_pass"),
    eval_selection(bio_stage1_rescue, "bio_P10_rescue"),
    eval_selection(stage2_pass, "bio_P15_pass"),
    eval_selection(stage2_rescue, "bio_P15_rescue"),
    eval_selection(bio_top10, "bio_final_top10"),
    eval_selection(bio_top3, "bio_final_top3"),
])

display(bio_eval_table)

bio_eval = {
    "selected_n": len(bio_top10),
    "mean_true_late_qp": float(bio_top10["true_late_qp"].mean()),
    "mean_true_qp_drop": float(bio_top10["true_qp_drop"].mean()),
    "mean_true_late_agg": float(bio_top10["true_late_agg"].mean()),
    "stable_rate": float(bio_top10["true_stable_label"].mean()),
    "top10_overlap_true_util_bio": topk_overlap(df["true_util_bio"], df["pred_util_bio"], TOP_N),
}
pd.DataFrame([bio_eval])

,label,n,mean_true_late_qp,mean_true_qp_drop,mean_true_late_agg,stable_rate
0,bio_P10_pass,79,3.428068e-07,0.300170,6.401296,0.493671
1,bio_P10_rescue,16,1.172433e-06,0.333055,6.075442,0.312500
2,bio_P15_pass,25,1.392966e-06,0.275884,6.485341,0.520000
3,bio_P15_rescue,8,2.701920e-07,0.339603,6.234431,0.250000
4,bio_final_top10,10,2.930531e-06,0.259613,6.994463,0.600000
5,bio_final_top3,3,8.256709e-06,0.163944,7.844594,1.000000

,selected_n,mean_true_late_qp,mean_true_qp_drop,mean_true_late_agg,stable_rate,top10_overlap_true_util_bio
0,10,0.000003,0.259613,6.994463,0.6,0.5

## Step 6A — Novel / ADC 3-bucket decision engine

In novel / ADC mode, quality is emphasized more strongly than in biosimilar mode.

So compared with biosimilar mode:

- aggregation threshold is stricter
- stability threshold is slightly stricter
- rescue margin is narrower
- productivity still matters, but low-quality clones are filtered more aggressively

We use the same 3-bucket logic:

- **pass** = strong candidates that clearly meet the criteria
- **rescue** = borderline but potentially valuable clones
- **fail** = clones that should be dropped

In [10]:
# --------------------------------------------------
# Step 6A — Novel / ADC 3-bucket decision engine
# --------------------------------------------------

NOVEL_AGG_MAX = 10.0
NOVEL_STABLE_PROB_MIN = 0.55

# rescue margin (stricter than biosimilar)
NOVEL_MARGIN_AGG = 2.0
NOVEL_MARGIN_STABLE = 0.08

novel = df.copy()

# ---------------------------
# Bucket definitions
# ---------------------------

# PASS (strict)
novel["pass_quality"] = novel["pred_late_agg"] <= NOVEL_AGG_MAX
novel["pass_stability"] = novel["pred_stable_prob"] >= NOVEL_STABLE_PROB_MIN
novel["bucket_pass"] = novel["pass_quality"] & novel["pass_stability"]

# RESCUE (borderline)
novel["near_quality"] = novel["pred_late_agg"].between(NOVEL_AGG_MAX, NOVEL_AGG_MAX + NOVEL_MARGIN_AGG)
novel["near_stability"] = novel["pred_stable_prob"].between(
    NOVEL_STABLE_PROB_MIN - NOVEL_MARGIN_STABLE,
    NOVEL_STABLE_PROB_MIN
)

novel["high_prod"] = novel["pred_late_qp"] >= novel["pred_late_qp"].quantile(0.85)

novel["bucket_rescue"] = (
    (~novel["bucket_pass"]) &
    novel["high_prod"] &
    (novel["near_quality"] | novel["near_stability"])
)

# FAIL
novel["bucket_fail"] = ~(novel["bucket_pass"] | novel["bucket_rescue"])

# ---------------------------
# Ranking
# ---------------------------
novel_pass = novel[novel["bucket_pass"]].copy()
novel_rescue = novel[novel["bucket_rescue"]].copy()

novel_pass["rank_metric"] = novel_pass["pred_late_qp"]
novel_rescue["rank_metric"] = novel_rescue["pred_late_qp"]

novel_pass = novel_pass.sort_values("rank_metric", ascending=False)
novel_rescue = novel_rescue.sort_values("rank_metric", ascending=False)

# ---------------------------
# Stage 1 selection (P10)
# ---------------------------
NOVEL_P10_PASS_N = 120
NOVEL_P10_RESCUE_N = 20

novel_stage1_pass = novel_pass.head(NOVEL_P10_PASS_N)
novel_stage1_rescue = novel_rescue.head(NOVEL_P10_RESCUE_N)

print("=== Novel / ADC Stage 1 (P10) ===")
print("Pass:", len(novel_stage1_pass))
print("Rescue:", len(novel_stage1_rescue))
print("Fail:", int(novel["bucket_fail"].sum()))

display(novel_stage1_pass[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in novel_stage1_pass.columns]])

display(novel_stage1_rescue[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in novel_stage1_rescue.columns]])

=== Novel / ADC Stage 1 (P10) ===
Pass: 44
Rescue: 20
Fail: 930

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
621,CLONE_3254,4.414624e-06,0.302129,8.575735,0.553073,7.251734e-06,0.204801,9.310199,1,0.501185,0.025047
314,CLONE_1619,2.235499e-06,0.208336,3.074035,0.890761,2.452274e-06,0.141343,4.494834,1,0.920042,0.000000
898,CLONE_3393,7.761064e-07,0.296605,8.548195,0.621659,7.938732e-07,0.360523,5.284487,0,0.511244,0.000000
490,CLONE_0355,5.121093e-07,0.303608,7.481896,0.574696,4.564358e-07,0.419802,7.810760,0,0.214447,0.000000
961,CLONE_1035,5.067668e-07,0.324348,8.473888,0.573182,4.534849e-07,0.427422,8.809331,0,0.266635,0.000000
206,CLONE_2358,4.766879e-07,0.290741,4.977838,0.661406,5.567181e-07,0.197321,4.869253,1,0.225138,0.000000
263,CLONE_4484,3.989533e-07,0.325480,3.720206,0.561986,4.399181e-07,0.316555,4.874848,0,0.201572,0.000000
134,CLONE_3969,3.872221e-07,0.295692,5.669074,0.713855,4.550859e-07,0.180621,5.380682,1,0.348253,0.000000
60,CLONE_2378,3.430713e-07,0.323846,3.692935,0.597291,3.347188e-07,0.300951,4.670409,0,0.289546,0.001648
690,CLONE_4335,3.375987e-07,0.281042,9.742523,0.734990,3.453973e-07,0.295673,10.147165,1,0.360620,0.000000
843,CLONE_0834,3.371535e-07,0.325388,6.171544,0.558512,3.740243e-07,0.308910,8.462860,0,0.072099,0.000000
477,CLONE_1757,3.333606e-07,0.278489,2.631215,0.719067,4.355070e-07,0.083806,1.773135,1,0.478711,0.003297
837,CLONE_0719,3.196800e-07,0.267984,3.690466,0.713607,3.202899e-07,0.331752,2.966982,0,0.205953,0.000000
951,CLONE_4735,3.191973e-07,0.329599,2.644784,0.577230,3.113780e-07,0.383725,3.864801,0,0.083469,0.004846
531,CLONE_1150,3.160824e-07,0.299298,2.740398,0.726761,2.797309e-07,0.411598,2.875040,0,0.262374,0.002807
274,CLONE_1834,3.097896e-07,0.290639,7.330778,0.607752,3.668220e-07,0.172878,6.882239,1,0.164822,0.005990
211,CLONE_1000,3.075764e-07,0.311457,6.083560,0.736135,3.653375e-07,0.239000,7.224040,1,0.402381,0.000000
141,CLONE_3822,3.009613e-07,0.288607,2.420374,0.725016,3.317974e-07,0.240727,3.817258,1,0.287875,0.000000
95,CLONE_4741,2.995351e-07,0.279822,6.229174,0.751862,3.739542e-07,0.127000,8.055819,1,0.373130,0.006298
297,CLONE_2226,2.820449e-07,0.298040,5.473257,0.650354,2.749554e-07,0.318427,7.448462,0,0.380251,0.000000
681,CLONE_0645,2.552438e-07,0.312491,5.382800,0.604788,1.991099e-07,0.485170,4.477654,0,0.332649,0.003238
248,CLONE_1783,2.542640e-07,0.279573,7.452893,0.713130,2.545850e-07,0.311945,7.023149,0,0.320760,0.000000
338,CLONE_3826,2.515496e-07,0.299175,6.460227,0.590380,2.757048e-07,0.243769,8.258205,1,0.226731,0.000000
787,CLONE_1039,2.485172e-07,0.314737,2.277451,0.559943,2.675613e-07,0.300345,0.242347,0,0.091518,0.001333
689,CLONE_4889,2.402883e-07,0.295121,6.901103,0.634809,2.584445e-07,0.209528,5.163608,1,0.441028,0.001653
335,CLONE_0894,2.245664e-07,0.282806,3.746408,0.705843,2.598114e-07,0.164092,1.110646,1,0.254002,0.000000
374,CLONE_2233,2.070127e-07,0.294595,5.110468,0.644229,2.406963e-07,0.191281,7.524516,1,0.152499,0.001087
493,CLONE_2844,1.969764e-07,0.300618,8.361858,0.650405,2.551812e-07,0.113319,8.013996,1,0.170488,0.001653
222,CLONE_4583,1.753103e-07,0.298994,5.358791,0.650631,1.727203e-07,0.350864,5.715349,0,0.061464,0.000000
414,CLONE_0411,1.673666e-07,0.314634,7.233027,0.593841,1.893654e-07,0.253331,10.356653,1,0.039042,0.000000
258,CLONE_0427,1.639864e-07,0.310195,6.274767,0.577450,1.762915e-07,0.283389,5.542990,1,0.070447,0.004204
928,CLONE_0888,1.633106e-07,0.323395,2.936778,0.603580,1.450686e-07,0.416051,2.039158,0,0.040802,0.000000
646,CLONE_3019,1.627431e-07,0.302170,5.853193,0.599622,1.734835e-07,0.292408,5.968056,1,0.126088,0.002837
836,CLONE_4982,1.549909e-07,0.342242,7.719418,0.559900,1.546631e-07,0.337191,7.198423,0,0.039772,0.000000
551,CLONE_2299,1.446317e-07,0.347150,7.916435,0.560967,1.468219e-07,0.332814,7.988565,0,0.018353,0.000000
922,CLONE_1331,1.439357e-07,0.339747,3.432833,0.567165,1.753984e-07,0.195520,5.779712,1,0.019133,0.000000
64,CLONE_0024,1.308352e-07,0.325299,3.420170,0.569337,1.176007e-07,0.409777,2.345602,0,0.042352,0.000000
659,CLONE_1205,1.261485e-07,0.330167,5.464606,0.578939,1.520479e-07,0.197443,7.158717,1,0.034701,0.000000
339,CLONE_1198,7.467273e-08,0.317202,2.741413,0.582642,8.647367e-08,0.284169,2.500992,1,0.036129,0.000000
376,CLONE_3236,7.425603e-08,0.330674,8.830857,0.599254,9.448878e-08,0.177502,8.135762,1,0.014087,0.000000
239,CLONE_4864,6.857986e-08,0.321504,7.734645,0.658978,6.694801e-08,0.404191,7.736952,0,0.001543,0.000000
454,CLONE_4687,4.601148e-08,0.357058,8.801351,0.555392,5.136494e-08,0.339681,7.330636,0,0.000000,0.000000
150,CLONE_1420,2.712112e-08,0.353765,6.959349,0.622043,1.105055e-08,0.458590,9.093829,0,0.000000,0.001575
528,CLONE_3538,2.705708e-08,0.414674,4.540212,0.556014,1.729141e-08,0.211141,6.157962,1,0.000000,0.001550

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
180,CLONE_4625,4.679723e-06,0.299615,9.050570,0.496845,1.506612e-05,0.145687,9.728748,1,0.728240,0.008469
505,CLONE_0048,4.626745e-06,0.418444,10.932292,0.336776,1.751650e-05,0.243664,11.123578,1,0.720186,0.013129
965,CLONE_4665,1.334567e-06,0.680854,11.363012,0.038890,9.387567e-07,0.726493,9.048022,0,0.135237,0.057142
801,CLONE_1505,5.694620e-07,0.497714,10.497773,0.032460,6.091065e-07,0.436365,11.902859,0,0.034412,0.001572
251,CLONE_4119,4.826748e-07,0.325585,3.773155,0.533421,4.881243e-07,0.292383,2.908559,1,0.212179,0.000000
115,CLONE_3602,4.559134e-07,0.339013,10.889757,0.500872,4.773866e-07,0.364849,12.370305,0,0.205479,0.001156
62,CLONE_4258,4.310919e-07,0.656405,10.029573,0.014869,4.168977e-07,0.659198,10.876121,0,0.010969,0.065558
966,CLONE_0151,3.846217e-07,0.336959,5.639886,0.546091,3.087592e-07,0.443713,6.537014,0,0.097044,0.000000
285,CLONE_3937,3.545450e-07,0.391644,11.398530,0.166454,3.938073e-07,0.315895,12.178303,0,0.009219,0.007756
558,CLONE_4801,3.525335e-07,0.499600,10.086772,0.046981,3.456956e-07,0.515201,11.561885,0,0.003035,0.001364
849,CLONE_4480,3.251827e-07,0.386956,10.569317,0.172259,2.611921e-07,0.502410,11.430376,0,0.113580,0.006230
432,CLONE_1873,3.217112e-07,0.281305,10.898906,0.702136,3.726886e-07,0.226222,10.342105,1,0.444635,0.001649
809,CLONE_4919,3.137509e-07,0.579600,10.304013,0.007365,2.637525e-07,0.653908,9.600915,0,0.004813,0.004206
988,CLONE_4850,3.079124e-07,0.416399,11.844067,0.101895,2.600363e-07,0.518530,11.694074,0,0.017516,0.006221
302,CLONE_3226,2.982971e-07,0.557019,10.142740,0.048638,2.544024e-07,0.610235,11.294864,0,0.009208,0.004379
202,CLONE_2768,2.900264e-07,0.425068,10.937394,0.111850,2.755202e-07,0.476787,12.561985,0,0.004686,0.004625
500,CLONE_3717,2.855180e-07,0.387746,10.333431,0.229972,3.317825e-07,0.312602,10.248515,0,0.034460,0.000000
663,CLONE_1045,2.838497e-07,0.305171,7.551278,0.493955,2.645873e-07,0.356933,9.767784,0,0.348932,0.002477
845,CLONE_4507,2.747384e-07,0.331586,7.717776,0.481751,2.956017e-07,0.283278,5.788807,1,0.249201,0.005983
850,CLONE_1747,2.524328e-07,0.365862,10.429868,0.314129,2.729994e-07,0.295369,11.060087,1,0.063546,0.000000

In [11]:
# --------------------------------------------------
# Novel / ADC Stage 2 (P15) refinement
# --------------------------------------------------

novel_stage2_pool = pd.concat([novel_stage1_pass, novel_stage1_rescue], ignore_index=True)

novel_stage2_pool["rank_metric"] = novel_stage2_pool["pred_late_qp"]
novel_stage2_pool = novel_stage2_pool.sort_values(
    ["rank_metric", "pred_stable_prob"],
    ascending=[False, False]
).copy()

NOVEL_P15_PASS_N = 25
NOVEL_P15_RESCUE_N = 5

novel_stage2_pass = novel_stage2_pool.head(NOVEL_P15_PASS_N).copy()
novel_stage2_rescue = novel_stage2_pool.iloc[
    NOVEL_P15_PASS_N:NOVEL_P15_PASS_N + NOVEL_P15_RESCUE_N
].copy()

print("=== Novel / ADC Stage 2 (P15) ===")
print("Pass:", len(novel_stage2_pass))
print("Rescue:", len(novel_stage2_rescue))

display(novel_stage2_pass[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in novel_stage2_pass.columns]])

display(novel_stage2_rescue[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in novel_stage2_rescue.columns]])

=== Novel / ADC Stage 2 (P15) ===
Pass: 25
Rescue: 5

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
44,CLONE_4625,4.679723e-06,0.299615,9.050570,0.496845,1.506612e-05,0.145687,9.728748,1,0.728240,0.008469
45,CLONE_0048,4.626745e-06,0.418444,10.932292,0.336776,1.751650e-05,0.243664,11.123578,1,0.720186,0.013129
0,CLONE_3254,4.414624e-06,0.302129,8.575735,0.553073,7.251734e-06,0.204801,9.310199,1,0.501185,0.025047
1,CLONE_1619,2.235499e-06,0.208336,3.074035,0.890761,2.452274e-06,0.141343,4.494834,1,0.920042,0.000000
46,CLONE_4665,1.334567e-06,0.680854,11.363012,0.038890,9.387567e-07,0.726493,9.048022,0,0.135237,0.057142
2,CLONE_3393,7.761064e-07,0.296605,8.548195,0.621659,7.938732e-07,0.360523,5.284487,0,0.511244,0.000000
47,CLONE_1505,5.694620e-07,0.497714,10.497773,0.032460,6.091065e-07,0.436365,11.902859,0,0.034412,0.001572
3,CLONE_0355,5.121093e-07,0.303608,7.481896,0.574696,4.564358e-07,0.419802,7.810760,0,0.214447,0.000000
4,CLONE_1035,5.067668e-07,0.324348,8.473888,0.573182,4.534849e-07,0.427422,8.809331,0,0.266635,0.000000
48,CLONE_4119,4.826748e-07,0.325585,3.773155,0.533421,4.881243e-07,0.292383,2.908559,1,0.212179,0.000000
5,CLONE_2358,4.766879e-07,0.290741,4.977838,0.661406,5.567181e-07,0.197321,4.869253,1,0.225138,0.000000
49,CLONE_3602,4.559134e-07,0.339013,10.889757,0.500872,4.773866e-07,0.364849,12.370305,0,0.205479,0.001156
50,CLONE_4258,4.310919e-07,0.656405,10.029573,0.014869,4.168977e-07,0.659198,10.876121,0,0.010969,0.065558
6,CLONE_4484,3.989533e-07,0.325480,3.720206,0.561986,4.399181e-07,0.316555,4.874848,0,0.201572,0.000000
7,CLONE_3969,3.872221e-07,0.295692,5.669074,0.713855,4.550859e-07,0.180621,5.380682,1,0.348253,0.000000
51,CLONE_0151,3.846217e-07,0.336959,5.639886,0.546091,3.087592e-07,0.443713,6.537014,0,0.097044,0.000000
52,CLONE_3937,3.545450e-07,0.391644,11.398530,0.166454,3.938073e-07,0.315895,12.178303,0,0.009219,0.007756
53,CLONE_4801,3.525335e-07,0.499600,10.086772,0.046981,3.456956e-07,0.515201,11.561885,0,0.003035,0.001364
8,CLONE_2378,3.430713e-07,0.323846,3.692935,0.597291,3.347188e-07,0.300951,4.670409,0,0.289546,0.001648
9,CLONE_4335,3.375987e-07,0.281042,9.742523,0.734990,3.453973e-07,0.295673,10.147165,1,0.360620,0.000000
10,CLONE_0834,3.371535e-07,0.325388,6.171544,0.558512,3.740243e-07,0.308910,8.462860,0,0.072099,0.000000
11,CLONE_1757,3.333606e-07,0.278489,2.631215,0.719067,4.355070e-07,0.083806,1.773135,1,0.478711,0.003297
54,CLONE_4480,3.251827e-07,0.386956,10.569317,0.172259,2.611921e-07,0.502410,11.430376,0,0.113580,0.006230
55,CLONE_1873,3.217112e-07,0.281305,10.898906,0.702136,3.726886e-07,0.226222,10.342105,1,0.444635,0.001649
12,CLONE_0719,3.196800e-07,0.267984,3.690466,0.713607,3.202899e-07,0.331752,2.966982,0,0.205953,0.000000

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
13,CLONE_4735,3.191973e-07,0.329599,2.644784,0.577230,3.113780e-07,0.383725,3.864801,0,0.083469,0.004846
14,CLONE_1150,3.160824e-07,0.299298,2.740398,0.726761,2.797309e-07,0.411598,2.875040,0,0.262374,0.002807
56,CLONE_4919,3.137509e-07,0.579600,10.304013,0.007365,2.637525e-07,0.653908,9.600915,0,0.004813,0.004206
15,CLONE_1834,3.097896e-07,0.290639,7.330778,0.607752,3.668220e-07,0.172878,6.882239,1,0.164822,0.005990
57,CLONE_4850,3.079124e-07,0.416399,11.844067,0.101895,2.600363e-07,0.518530,11.694074,0,0.017516,0.006221

In [12]:
# --------------------------------------------------
# Novel / ADC final selection
# --------------------------------------------------

novel_final_pool = pd.concat([novel_stage2_pass, novel_stage2_rescue], ignore_index=True)
novel_final_pool = novel_final_pool.sort_values(
    ["pred_late_qp", "pred_stable_prob"],
    ascending=[False, False]
).copy()

novel_top10 = novel_final_pool.head(TOP_N).copy()
novel_top3 = novel_final_pool.head(TOP_STAGE2).copy()

print("=== Novel / ADC Final Selection ===")
print("Final top10:", len(novel_top10))
print("Final top3:", len(novel_top3))

display(novel_top10[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in novel_top10.columns]])

display(novel_top3[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in novel_top3.columns]])

=== Novel / ADC Final Selection ===
Final top10: 10
Final top3: 3

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
0,CLONE_4625,4.679723e-06,0.299615,9.050570,0.496845,1.506612e-05,0.145687,9.728748,1,0.728240,0.008469
1,CLONE_0048,4.626745e-06,0.418444,10.932292,0.336776,1.751650e-05,0.243664,11.123578,1,0.720186,0.013129
2,CLONE_3254,4.414624e-06,0.302129,8.575735,0.553073,7.251734e-06,0.204801,9.310199,1,0.501185,0.025047
3,CLONE_1619,2.235499e-06,0.208336,3.074035,0.890761,2.452274e-06,0.141343,4.494834,1,0.920042,0.000000
4,CLONE_4665,1.334567e-06,0.680854,11.363012,0.038890,9.387567e-07,0.726493,9.048022,0,0.135237,0.057142
5,CLONE_3393,7.761064e-07,0.296605,8.548195,0.621659,7.938732e-07,0.360523,5.284487,0,0.511244,0.000000
6,CLONE_1505,5.694620e-07,0.497714,10.497773,0.032460,6.091065e-07,0.436365,11.902859,0,0.034412,0.001572
7,CLONE_0355,5.121093e-07,0.303608,7.481896,0.574696,4.564358e-07,0.419802,7.810760,0,0.214447,0.000000
8,CLONE_1035,5.067668e-07,0.324348,8.473888,0.573182,4.534849e-07,0.427422,8.809331,0,0.266635,0.000000
9,CLONE_4119,4.826748e-07,0.325585,3.773155,0.533421,4.881243e-07,0.292383,2.908559,1,0.212179,0.000000

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
0,CLONE_4625,0.000005,0.299615,9.050570,0.496845,0.000015,0.145687,9.728748,1,0.728240,0.008469
1,CLONE_0048,0.000005,0.418444,10.932292,0.336776,0.000018,0.243664,11.123578,1,0.720186,0.013129
2,CLONE_3254,0.000004,0.302129,8.575735,0.553073,0.000007,0.204801,9.310199,1,0.501185,0.025047

In [13]:
novel_eval_table = pd.DataFrame([
    eval_selection(novel_stage1_pass, "novel_P10_pass"),
    eval_selection(novel_stage1_rescue, "novel_P10_rescue"),
    eval_selection(novel_stage2_pass, "novel_P15_pass"),
    eval_selection(novel_stage2_rescue, "novel_P15_rescue"),
    eval_selection(novel_top10, "novel_final_top10"),
    eval_selection(novel_top3, "novel_final_top3"),
])

display(novel_eval_table)

novel_eval = {
    "selected_n": len(novel_top10),
    "mean_true_late_qp": float(novel_top10["true_late_qp"].mean()),
    "mean_true_qp_drop": float(novel_top10["true_qp_drop"].mean()),
    "mean_true_late_agg": float(novel_top10["true_late_agg"].mean()),
    "stable_rate": float(novel_top10["true_stable_label"].mean()),
    "top10_overlap_true_util_novel": topk_overlap(df["true_util_novel"], df["pred_util_novel"], TOP_N),
}
pd.DataFrame([novel_eval])

,label,n,mean_true_late_qp,mean_true_qp_drop,mean_true_late_agg,stable_rate
0,novel_P10_pass,44,4.753548e-07,0.282417,5.951956,0.522727
1,novel_P10_rescue,20,1.970686e-06,0.418986,10.101245,0.300000
2,novel_P15_pass,25,2.074580e-06,0.337662,7.954513,0.400000
3,novel_P15_rescue,5,2.963439e-07,0.428127,6.983414,0.200000
4,novel_final_top10,10,4.602641e-06,0.339848,8.042138,0.500000
5,novel_final_top3,3,1.327812e-05,0.198051,10.054175,1.000000

,selected_n,mean_true_late_qp,mean_true_qp_drop,mean_true_late_agg,stable_rate,top10_overlap_true_util_novel
0,10,0.000005,0.339848,8.042138,0.5,0.3

## Step 7 — Compare decision modes

This step makes it easier to see how the selected clone sets differ
between biosimilar mode and novel / ADC mode.

In [14]:
mode_compare = pd.DataFrame([
    {"mode": "biosimilar", **bio_eval},
    {"mode": "novel/ADC", **novel_eval},
])

display(mode_compare)

bio_ids = set(bio_top10["clone_id"])
novel_ids = set(novel_top10["clone_id"])

print("Overlap between selected clone sets:", len(bio_ids & novel_ids))
print("Biosimilar-only:", sorted(list(bio_ids - novel_ids))[:10])
print("Novel-only:", sorted(list(novel_ids - bio_ids))[:10])

,mode,selected_n,mean_true_late_qp,mean_true_qp_drop,mean_true_late_agg,stable_rate,top10_overlap_true_util_bio,top10_overlap_true_util_novel
0,biosimilar,10,0.000003,0.259613,6.994463,0.6,0.5,NaN
1,novel/ADC,10,0.000005,0.339848,8.042138,0.5,NaN,0.3

Overlap between selected clone sets: 7
Biosimilar-only: ['CLONE_2358', 'CLONE_2723', 'CLONE_2759']
Novel-only: ['CLONE_0048', 'CLONE_1505', 'CLONE_4665']

## Step 8 — Utility-based weight sweep (optional analysis)

This section is not the main deployment rule.

Instead, it helps us explore whether different utility weight combinations
could improve top-k clone selection.

This is useful for:
- comparing biosimilar vs novel priorities
- tuning future SDL decision rules
- stress-testing the decision engine

In [15]:
grid_bio = {
    "w_qp": [0.5, 1.0, 1.5, 2.0],
    "w_drop": [0.5, 1.0, 1.5, 2.0],
    "w_agg": [0.0, 0.1, 0.2, 0.3],
}

grid_novel = {
    "w_qp": [0.5, 1.0, 1.5],
    "w_drop": [0.5, 1.0, 1.5],
    "w_agg": [0.5, 1.0, 1.5, 2.0],
}

ELITE_FRACS = [0.10]
K_LIST = [5, 10, 20]

def mark_elite(df, util_col, frac):
    thr = df[util_col].quantile(1 - frac)
    return (df[util_col] >= thr).astype(int)

def run_sweep(base_df, mode_name, grid, true_util_col):
    rows = []
    work = base_df.copy()

    for w_qp in grid["w_qp"]:
        for w_drop in grid["w_drop"]:
            for w_agg in grid["w_agg"]:
                work["pred_util_tmp"] = (
                    w_qp * z(work["pred_late_qp"])
                    - w_drop * z(work["pred_qp_drop"])
                    - w_agg * z(work["pred_late_agg"])
                )

                for frac in ELITE_FRACS:
                    elite_col = f"elite_{int(frac*100)}"
                    work[elite_col] = mark_elite(work, true_util_col, frac)

                    for k in K_LIST:
                        rows.append({
                            "mode": mode_name,
                            "w_qp": w_qp,
                            "w_drop": w_drop,
                            "w_agg": w_agg,
                            "elite_frac": frac,
                            "k": k,
                            "precision@k": precision_at_k_df(work, "pred_util_tmp", elite_col, k),
                            "ndcg@k": ndcg_at_k_df(work, "pred_util_tmp", elite_col, k),
                        })
    return pd.DataFrame(rows)

bio_sweep = run_sweep(df, "biosimilar", grid_bio, "true_util_bio")
novel_sweep = run_sweep(df, "novel/ADC", grid_novel, "true_util_novel")

display(bio_sweep.sort_values(["precision@k", "ndcg@k"], ascending=False).head(10))
display(novel_sweep.sort_values(["precision@k", "ndcg@k"], ascending=False).head(10))

          mode  w_qp  w_drop  w_agg  elite_frac  k  precision@k  ndcg@k
0   biosimilar   0.5     0.5    0.0         0.1  5          1.0     1.0
3   biosimilar   0.5     0.5    0.1         0.1  5          1.0     1.0
6   biosimilar   0.5     0.5    0.2         0.1  5          1.0     1.0
9   biosimilar   0.5     0.5    0.3         0.1  5          1.0     1.0
21  biosimilar   0.5     1.0    0.3         0.1  5          1.0     1.0
48  biosimilar   1.0     0.5    0.0         0.1  5          1.0     1.0
51  biosimilar   1.0     0.5    0.1         0.1  5          1.0     1.0
54  biosimilar   1.0     0.5    0.2         0.1  5          1.0     1.0
57  biosimilar   1.0     0.5    0.3         0.1  5          1.0     1.0
60  biosimilar   1.0     1.0    0.0         0.1  5          1.0     1.0

         mode  w_qp  w_drop  w_agg  elite_frac  k  precision@k  ndcg@k
0   novel/ADC   0.5     0.5    0.5         0.1  5          1.0     1.0
3   novel/ADC   0.5     0.5    1.0         0.1  5          1.0     1.0
6   novel/ADC   0.5     0.5    1.5         0.1  5          1.0     1.0
9   novel/ADC   0.5     0.5    2.0         0.1  5          1.0     1.0
12  novel/ADC   0.5     1.0    0.5         0.1  5          1.0     1.0
15  novel/ADC   0.5     1.0    1.0         0.1  5          1.0     1.0
18  novel/ADC   0.5     1.0    1.5         0.1  5          1.0     1.0
21  novel/ADC   0.5     1.0    2.0         0.1  5          1.0     1.0
27  novel/ADC   0.5     1.5    1.0         0.1  5          1.0     1.0
30  novel/ADC   0.5     1.5    1.5         0.1  5          1.0     1.0

## Step 9 — Identify borderline but potentially rescuable clones

These are clones that:

- have strong predicted productivity
- are close to passing the quality or stability threshold
- may be interesting for future process-rescue strategies

This section is exploratory, but it is important for long-term SDL design.

In [16]:
# Example: near-pass clones
MARGIN_AGG = 2.0
MARGIN_STABLE = 0.05

borderline = df.copy()

borderline["high_prod"] = borderline["pred_late_qp"] >= borderline["pred_late_qp"].quantile(0.90)
borderline["near_quality"] = borderline["pred_late_agg"].between(BIO_AGG_MAX, BIO_AGG_MAX + MARGIN_AGG)
borderline["near_stability"] = borderline["pred_stable_prob"].between(BIO_STABLE_PROB_MIN - MARGIN_STABLE, BIO_STABLE_PROB_MIN)

resc_candidates = borderline[
    borderline["high_prod"] & (borderline["near_quality"] | borderline["near_stability"])
].copy()

resc_candidates = resc_candidates.sort_values("pred_late_qp", ascending=False)

print("Potentially rescuable candidates:", len(resc_candidates))
display(resc_candidates[[
    "clone_id",
    "pred_late_qp", "pred_qp_drop", "pred_late_agg", "pred_stable_prob",
    "true_late_qp", "true_qp_drop", "true_late_agg", "true_stable_label"
] + [c for c in ["pred_super_prob", "pred_aggr_prob"] if c in resc_candidates.columns]].head(20))

Potentially rescuable candidates: 1

,clone_id,pred_late_qp,pred_qp_drop,pred_late_agg,pred_stable_prob,true_late_qp,true_qp_drop,true_late_agg,true_stable_label,pred_super_prob,pred_aggr_prob
180,CLONE_4625,0.000005,0.299615,9.05057,0.496845,0.000015,0.145687,9.728748,1,0.72824,0.008469

## Output of Notebook 04b

This notebook converts predicted late-stage outcomes into actual clone selection decisions.

### Main outputs
- biosimilar-mode selected clones
- novel / ADC-mode selected clones
- offline evaluation against synthetic truth
- utility-based comparison of scoring rules
- exploratory list of borderline / rescuable candidates

### Pipeline meaning
- **Notebook 03b = prediction engine**
- **Notebook 04b = decision engine**

This separation makes the workflow more extensible for future SDL systems, where:
- thresholds may change
- product profiles may differ
- rescue strategies may be added without retraining the prediction model